version: '3.8'

services:
  app:
    build:
      context: ./api
      dockerfile: Dockerfile
    image: laravel_app
    container_name: laravel_app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./api:/var/www
      - ./api/vendor:/var/www/vendor
    networks:
      - laravel

  webserver:
    image: nginx:alpine
    container_name: nginx
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ./api:/var/www
      - ./api/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - laravel

  mysql:
    image: mysql:5.7
    container_name: mysql
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: laravel
      MYSQL_PASSWORD: laravel
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - laravel

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: vue_frontend
    container_name: vue_frontend
    ports:
      - "8080:8080"
    volumes:
      - ./frontend:/app
    networks:
      - laravel

networks:
  laravel:

volumes:
  mysql_data:
